# Generated by Django 5.2.3 on 2025-06-27 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ("-date",)},
        ),
    ]
