# Generated by Django 5.2.3 on 2025-06-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_event_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="excerpt",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
