# Generated by Django 5.2.3 on 2025-06-30 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_event_excerpt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="comment",
            new_name="content",
        ),
    ]
