# Generated by Django 5.2.3 on 2025-07-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_comment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='manually_edited',
            field=models.BooleanField(default=False),
        ),
    ]
