# Generated by Django 5.2.3 on 2025-07-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_comment_manually_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
