# Generated by Django 5.2.3 on 2025-07-18 16:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder_image', max_length=255, null=True, verbose_name='image'),
        ),
    ]
